language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/phpunit

after_script: ./bin/scrutinizer.sh
